using UnityEngine;

public class Drivetrain : MonoBehaviour
{
	public enum Transmissions
	{
		RWD = 0,
		FWD = 1,
		AWD = 2,
		XWD = 3,
	}

	public bool engineTorqueFromFile;
	public int torqueRPMValuesLen;
	public CarController carController;
	public FuelTank[] fuelTanks;
	public Wheel[] poweredWheels;
	public float maxPower;
	public float maxPowerRPM;
	public float maxTorque;
	public float maxTorqueRPM;
	public float originalMaxPower;
	public float maxNetPower;
	public float maxNetPowerRPM;
	public float maxNetTorque;
	public float maxNetTorqueRPM;
	public float torque;
	public float wheelTireVelo;
	public float minRPM;
	public float maxRPM;
	public bool canStall;
	public bool startEngine;
	public bool revLimiter;
	public float revLimiterTime;
	public bool revLimiterTriggered;
	public bool revLimiterReleased;
	public float engineInertia;
	public float drivetrainInertia;
	public float engineFrictionFactor;
	public Vector3 engineOrientation;
	public Transmissions transmission;
	public float[] gearRatios;
	public int neutral;
	public int first;
	public int firstReverse;
	public float finalDriveRatio;
	public float differentialLockCoefficient;
	public bool shifter;
	public bool automatic;
	public bool autoReverse;
	public float shiftDownRPM;
	public float shiftUpRPM;
	public float shiftTime;
	public float clutchMaxTorque;
	public bool autoClutch;
	public float engageRPM;
	public float disengageRPM;
	public float _fuelConsumptionAtCostantSpeed;
	public float _fuelConsumptionSpeed;
	public float currentConsumption;
	public float istantConsumption;
	public float RPMAtSpeedInLastGear;
	public float clutchTorqueMultiplier;
	public float clutchEngageSpeed;
	public float throttle;
	public float idlethrottle;
	public float startTorque;
	public bool shiftTriggered;
	public bool soundPlayed;
	public float clutchDragImpulse;
	public float differentialSpeed;
	public bool engaging;
	public bool CanShiftAgain;
	public int gear;
	public float rpm;
	public float angularVelo2RPM;
	public float RPM2angularVelo;
	public float KW2CV;
	public float CV2KW;
	public float maxPowerDriveShaft;
	public float currentPower;
	public float curveFactor;
	public float frictionTorque;
	public float powerMultiplier;
	public float externalMultiplier;
	public float ratio;
	public float lastGearRatio;
	public bool changingGear;
	public float drivetrainFraction;
	public float velo;
	public float RPMAt130Kmh;
}
